### ISSUE TITLE
Class 'Collective\Html\Formbuilder' not found

### ISSUE THREAD

**Issue by zhiephie** [bestmomo/laravel5-example#19]
see this http://prntscr.com/695upr

**Comment by bestmomo** [comment]
Hello,

Looks like an autoload issue. Did you try **composer dumpautoload** or **php artisan clear-compiled** ?

**Comment by zhiephie** [comment]
I tried composer dumpautoload or php artisan compiled and the results Class 'Collective \ html \ Formbuilder' not found

**Comment by bestmomo** [comment]
Did you change something to composer.php ?

In *vendor/composer/autoload_classmap.php* is there this line :
```
'Collective\\Html\\FormBuilder' => $vendorDir . '/laravelcollective/html/src/FormBuilder.php',
```

**Comment by zhiephie** [comment]
no, i'm look in vendor/composer/autoload_classmap.php is this line not found

``` 'Collective\\Html\\FormBuilder' => $vendorDir . '/laravelcollective/html/src/FormBuilder.php', ```

**Comment by bestmomo** [comment]
You should do a new fresh install and see if it works.

**Comment by zhiephie** [comment]
ok, i'm try it again
