### ISSUE TITLE
php artisan route:scan not working

### ISSUE THREAD

**Issue by mh-jamil** [bestmomo/laravel5-example#2]
I've followed all steps to install the project. But when I do php artisan route:scan following error occurs:

Exception with message Class Doctrine\Common\AnnotationRegistry not found

I've attached a screenshot of the error for your convenience. 

![issue](https://cloud.githubusercontent.com/assets/10434700/5645564/083b409e-9693-11e4-958d-93fdc2b9bb3e.png)

**Comment by mh-jamil** [comment]
Ok, so I need to download the zip files again and do the installation from start?

**Comment by bestmomo** [comment]
Yes

**Comment by bestmomo** [comment]
At last I have removed annotations, so no more route:scan  ;)

**Comment by mh-jamil** [comment]
It worked. I'm reviewing the project. Great work, going to learn a lot of things from it. 

Many Thanks :+1:

**Comment by bestmomo** [comment]
You're welcome ;)

**Comment by deepakgarg9121** [comment]
Dear sir..i am getting some problem in bestmomo file manager.when i open it the new popup window will be open.but in right side there is loader is moving.i wait for very much time.but the Loader is not stoping.i follow all the step to setup this.

**Comment by bestmomo** [comment]
Hi,
What is the url you can read in filemanager window ?

**Comment by deepakgarg9121** [comment]
http://localhost/laravelAdmin/public/filemanager/index.html

where laravelAdmin is my project name..pLease help me
