### ISSUE TITLE
Class 'Collective\Html\Formbuilder' not found

### ISSUE THREAD

**Issue by Janaksan** [bestmomo/laravel5-example#20]
![q1](https://cloud.githubusercontent.com/assets/3922746/6438445/03ca9f1a-c0ef-11e4-9567-0ca32d602031.png)

FatalErrorException in FormBuilder.php line 3:
Class 'Collective\Html\Formbuilder' not found

**Comment by bestmomo** [comment]
Is it a fresh installation or did you make a change on previous installation ?

**Comment by Janaksan** [comment]
fresh installation from your repository.and i follow your installation step

**Comment by bestmomo** [comment]
In vendor/composer/autoload_classmap.php is there this line :
```
'Collective\\Html\\FormBuilder' => $vendorDir . '/laravelcollective/html/src/FormBuilder.php'
```

**Comment by Janaksan** [comment]
yes there

**Comment by Janaksan** [comment]
![q2](https://cloud.githubusercontent.com/assets/3922746/6438734/03fcb830-c0f2-11e4-970b-d6feb77fb251.png)

**Comment by bestmomo** [comment]
All seems ok... there is something weird. Try a new fresh intallation.

**Comment by Janaksan** [comment]
no bro .same problem after fresh install.

**Comment by bestmomo** [comment]
I dont understand what happens for you. I've made an install with the repo to see if there is some bug but all works fine for me. Did you try a basic Laravel installation with this package ?

**Comment by combaudouo** [comment]
Had the same issue with my code. Not in front on my computer right now, but it was due to the Submit field that I used on a project using L4 -> I had to add (or remove i don't remove) a parameter to make it work.

Hope that helps

**Comment by zlati** [comment]
I also encountered this. Actually, it is looking for "\Collective\Html\Form**b**uilder", while the actual class is "Form**B**uilder". So you just need to capitalize the "B" in *app/Services/Html/FormBuilder.php* so it becomes "class FormBuilder extends \Collective\Html\Form**B**uilder {" That's all.

**Comment by serdar-turkmen** [comment]
FatalErrorException in FormBuilder.php line 3:
Class 'Collective\Html\Formbuilder' not found What we do?

**Comment by bestmomo** [comment]
Sorry, I'm on Windows and it doesn't wonder about that ! I've corrected it in [this commit](https://github.com/bestmomo/laravel5-example/commit/885d3ccdb8efe58daaf104156cd1c4567a70c4b0)
