### ISSUE TITLE
Media Controller not found

### ISSUE THREAD

**Issue by thaigialai1987** [bestmomo/laravel5-example#24]
FatalErrorException in BlogController.php line 153:
Class 'App\Services\Medias' not found.
I not see Medias.php in services folder.
Please fix.
Thanks

**Comment by bestmomo** [comment]
I've made a rollback of the last commit in [this commit](https://github.com/bestmomo/laravel5-example/commit/02bb845e24cee54dcc35f390829efab3dce85a2b). There is something I must dig deeper in filemanager folder management.
