### ISSUE TITLE
Congratulations and thank

### ISSUE THREAD

**Issue by Orthophilos** [bestmomo/laravel5-example#26]
Congratulations to the developer, very quite code, I'm learning so much. Thanks

**Comment by bestmomo** [comment]
yw ;)

**Comment by Gazoo101** [comment]
I also wanted to re-iterate my appreciation for what you've built here as an example.

I've put together my own website using laravel 4 & 5 ( www.lasselaursen.com ), but it lacks any sort of dynamic development which has started to annoy me enough to do something about.

But adding a blog that can incorporate images easily (or code snippets) is not a small task and having your example to go by will make the whole process much easier. I looked at a few alternatives (wordpress, etc.) but none of them seemed ideal to integrate with Laravel.

The only decision I've yet to really make my mind up about is if I should now use your code base and change it to fit my website or vice versa.

Either way, thanks for this awesome code repo!

**Comment by bestmomo** [comment]
I'm glad if my code is useful. I think the best way is to find your own coding style.

Best regards.

**Comment by Gazoo101** [comment]
I did end up coding my own while getting a lot of inspiration from your framework - so thanks again for creating it!
