### ISSUE TITLE
Dropdown Navigation

### ISSUE THREAD

**Issue by haucongle** [bestmomo/laravel5-example#27]
I want to create a navigation with dropdown in you template.blade.php. I used class="dropdown" in bootstrap and add CDN bootstrap but it not working. Can you help me?
PS: sorry about my bad english grammar.

**Comment by bestmomo** [comment]
Bootstrap (V3.2) is already loaded with the template. To add a dropdown in navbar use standard bootstrap code : 
```
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
```

**Comment by haucongle** [comment]
Yes, i copied pasted into template.blade.php but Google Chrome only show Dropdown and caret sign. Items 'Action', 'Another action', .. not visible.

**Comment by bestmomo** [comment]
Where do you put this code ?

**Comment by haucongle** [comment]
Sorry, it worked. I don't know WHY?

**Comment by bestmomo** [comment]
perfect if it works ;)
