### ISSUE TITLE
[Error] Update CKeditor

### ISSUE THREAD

**Issue by haucongle** [bestmomo/laravel5-example#28]
Hello, I download new ckeditor at http://ckeditor.com/download, I choose Full package. I uncompress and put it in public folder which replace your ckeditor. But in comment part in Blog Tab, there is no anything although i login!
Can your help me?

**Comment by bestmomo** [comment]
Hello,

I just tried with last version :
- preset standard
- plugin code snippet
- skin Kama
- add french language
All downloaded and replaced existing in public, all is working fine for me.

I have updated the repository with [this commit](https://github.com/bestmomo/laravel5-example/commit/7e01302f7202f07724d0ea60d13ac66aa3e1f6dc), so you can get it at last version.

**Comment by haucongle** [comment]
Thank you very much
