### ISSUE TITLE
add /blog into backoffice

### ISSUE THREAD

**Issue by lemirage** [bestmomo/laravel5-example#30]
hello ,
View/back/blog/template.blade.php
on line 28	
{!! url('/') . '/blog  ' . Form::text('slug', null, ['id' => 'permalien']) !!}
to have the real front url ;)

**Comment by bestmomo** [comment]
Good catch ;)
Corrected with [this commit](https://github.com/bestmomo/laravel5-example/commit/5764b4a861a058706461a6988eaa91e114f44888).
