### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 53:

### ISSUE THREAD

**Issue by GuGuss** [bestmomo/laravel5-example#31]
Hi,

I'm trying your example on [Platform.sh](https://platform.sh), and I got the following error when logging in:

```
TokenMismatchException in VerifyCsrfToken.php line 53
```

You can check my site [here](http://master-xdqowioyzb6gq.eu.platform.sh/) or [my fork](https://github.com/GuGuss/laravel5-example) loading the proper Platform.sh database configuration.

Thanks,

GuGuss

**Comment by bestmomo** [comment]
Hi,

The issue is on all forms (I also tested contact form). Are you sure you 
have good PHP config ?

Regards,

Maurice

Le 02/09/2015 16:54, Augustin Delaporte a écrit :
>
> Hi,
>
> I'm trying your example on Platform.sh, and I got the following error 
> when logging in:
>
> |TokenMismatchException in VerifyCsrfToken.php line 53 |
>
> You can check my site here 
> <http://master-xdqowioyzb6gq.eu.platform.sh/> or my fork 
> <https://github.com/GuGuss/laravel5-example> loading the proper 
> Platform.sh database configuration.
>
> Thanks,
>
> GuGuss
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bestmomo/laravel5-example/issues/31>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by bestmomo** [comment]
And did you generate a key (|php artisan key:generate)| in .env file ?

Le 02/09/2015 16:54, Augustin Delaporte a écrit :
>
> Hi,
>
> I'm trying your example on Platform.sh, and I got the following error 
> when logging in:
>
> |TokenMismatchException in VerifyCsrfToken.php line 53 |
>
> You can check my site here 
> <http://master-xdqowioyzb6gq.eu.platform.sh/> or my fork 
> <https://github.com/GuGuss/laravel5-example> loading the proper 
> Platform.sh database configuration.
>
> Thanks,
>
> GuGuss
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bestmomo/laravel5-example/issues/31>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by GuGuss** [comment]
Hi, you're right, it's working now!

I emptied the ``sessions`` folder and it now works...

Thanks!

Laravel seems cool. I'm glad it works on Platform.sh :+1:
