### ISSUE TITLE
What about Testing ???

### ISSUE THREAD

**Issue by imanghafoori1** [bestmomo/laravel5-example#35]
I cried All the night...
The tests folder was all empty. :((

**Comment by bestmomo** [comment]
Sorry ^^

**Comment by imanghafoori1** [comment]
your app was full of lessons... thanks.
but the moment I just clicked on the tests folder to see a bunch of nice tests...
became a drama for me.
Sadly, the tests folder was all empty. :(

**Comment by imanghafoori1** [comment]
Do you what me to create some integration tests on this app ?

**Comment by bestmomo** [comment]
Sure, it's an open project.
