### ISSUE TITLE
Blog search is not functioning correctly

### ISSUE THREAD

**Issue by sopnopriyo** [bestmomo/laravel5-example#38]
The search in the blog page does not display the item found in the blog.

**Comment by bestmomo** [comment]
Hello,

Could you show an example of abortive search ?

**Comment by sopnopriyo** [comment]
![software-development](https://cloud.githubusercontent.com/assets/7261420/11524255/3575e338-9904-11e5-80ca-d2b5913a4d14.jpg)

**Comment by bestmomo** [comment]
The search is on summary and content, not on title, do you think it'd be good to also search on it ?

**Comment by sopnopriyo** [comment]
I think title is the major key of a post.So main keyword of a post might be in the title.It would be better if you also include it.

**Comment by bestmomo** [comment]
Done on [this commit](https://github.com/bestmomo/laravel5-example/commit/03a9aee50bf82bfb1c81b461b35d9c6912830c4e).
