### ISSUE TITLE
  ErrorException in UserRepository.php line 53

### ISSUE THREAD

**Issue by chenchaochen** [bestmomo/laravel5-example#39]
Hi, 

When I registered a new user, I got the error messages as below. 

ErrorException in UserRepository.php line 53
Trying to get property of non-object

1. in UserRepository.php line 53
2.at HandleExceptions->handleError('8', 'Trying to get property of non-object', 'C:\xampp\htdocs\laravel5-example\app\Repositories\UserRepository.php', '53', array('user' => object(User), 'inputs' => array('_token' => 'ETs1bfntR5oslSfENuxHHhhXorNaJY1WPQxHwzt9', 'username' => 'Evans', 'email' => 'evans.daoapp@gmail.com', 'password' => '12qwaszx', 'password_confirmation' => '12qwaszx', 'address' => ''), 'role_user' => null)) in UserRepository.php line 53
3.at UserRepository->save(object(User), array('_token' => 'ETs1bfntR5oslSfENuxHHhhXorNaJY1WPQxHwzt9', 'username' => 'Evans', 'email' => 'evans.daoapp@gmail.com', 'password' => '12qwaszx', 'password_confirmation' => '12qwaszx', 'address' => '')) in UserRepository.php line 145
4.at UserRepository->store(array('_token' => 'ETs1bfntR5oslSfENuxHHhhXorNaJY1WPQxHwzt9', 'username' => 'Evans', 'email' => 'evans.daoapp@gmail.com', 'password' => '12qwaszx', 'password_confirmation' => '12qwaszx', 'address' => ''), 'J2wwFd2WPsWM0g8BaQb51DxbCPa2lM') in AuthController.php line 108
5.at AuthController->postRegister(object(RegisterRequest), object(UserRepository))
6.at call_user_func_array(array(object(AuthController), 'postRegister'), array(object(RegisterRequest), object(UserRepository))) in Controller.php line 256
7.at Controller->callAction('postRegister', array(object(RegisterRequest), object(UserRepository))) in ControllerDispatcher.php line 164
8.at ControllerDispatcher->call(object(AuthController), object(Route), 'postRegister') in ControllerDispatcher.php line 112
9.at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
10.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
11.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in RedirectIfAuthenticated.php line 41
12.at RedirectIfAuthenticated->handle(object(Request), object(Closure))
13.at call_user_func_array(array(object(RedirectIfAuthenticated), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
14.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
15.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
16.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 114
17.at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'postRegister') in ControllerDispatcher.php line 69
18.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Auth\AuthController', 'postRegister') in Route.php line 203
19.at Route->runWithCustomDispatcher(object(Request)) in Route.php line 134
20.at Route->run(object(Request)) in Router.php line 708
21.at Router->Illuminate\Routing\{closure}(object(Request))
22.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
23.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
24.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
25.at Pipeline->then(object(Closure)) in Router.php line 710
26.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 675
27.at Router->dispatchToRoute(object(Request)) in Router.php line 635
28.at Router->dispatch(object(Request)) in Kernel.php line 236
29.at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
30.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
31.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in App.php line 56
32.at App->handle(object(Request), object(Closure))
33.at call_user_func_array(array(object(App), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
34.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
35.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 17
36.at VerifyCsrfToken->handle(object(Request), object(Closure))
37.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
38.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
39.at ShareErrorsFromSession->handle(object(Request), object(Closure))
40.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
41.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
42.at StartSession->handle(object(Request), object(Closure))
43.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
44.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
45.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
46.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
47.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
48.at EncryptCookies->handle(object(Request), object(Closure))
49.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
50.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
51.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
52.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
53.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
54.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
55.at Pipeline->then(object(Closure)) in Kernel.php line 122
56.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
57.at Kernel->handle(object(Request)) in index.php line 53

Is anything I need to edit or fix?
Thanks

**Comment by bestmomo** [comment]
Hi,

Looks like there is something weird with your roles. What did you change on them ?

Check if you get something on line 52 in `UserRepository` :
```
$role_user = $this->role->where('slug', 'user')->first();
dd($role_user);
```

**Comment by chenchaochen** [comment]
Hi, 

Thanks for your immediate response. I'm very impressed  :+1: 
I didn't change anything in code, just create a database same as .env, Updated composer and done migration and key:generate. 

the dd($role_user) returned null. Seems something wrong with my role.

Thanks

**Comment by bestmomo** [comment]
Hi,

Did you seed the database ?

**Comment by chenchaochen** [comment]
I'm sorry, my bad. 

I re-run seed command, and it returned seemed normally 

Role {#245 ▼
  #table: "roles"
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:5 [▼
    "id" => 3
    "title" => "User"
    "slug" => "user"
    "created_at" => "2015-12-07 09:30:50"
    "updated_at" => "2015-12-07 09:30:50"
  ]
  #original: array:5 [▼
    "id" => 3
    "title" => "User"
    "slug" => "user"
    "created_at" => "2015-12-07 09:30:50"
    "updated_at" => "2015-12-07 09:30:50"
  ]
  #relations: []
  #hidden: []
  #visible: []
  #appends: []
  #fillable: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
}

**Comment by chenchaochen** [comment]
Hi, 

I remarked //dd($role_user); and tried again, a new exception appeared

Swift_TransportException in AbstractSmtpTransport.php line 383:

Expected response code 220 but got code "554", with message "554 5.7.1 <unknown[114.42.221.190]:54283>: Client host rejected: Access denied
 "

in AbstractSmtpTransport.php line 383
2.at Swift_Transport_AbstractSmtpTransport->_assertResponseCode('554 5.7.1 <unknown[114.42.221.190]:54283>: Client host rejected: Access denied ', array('220')) in AbstractSmtpTransport.php line 289
3.at Swift_Transport_AbstractSmtpTransport->_readGreeting() in AbstractSmtpTransport.php line 117
4.at Swift_Transport_AbstractSmtpTransport->start() in Mailer.php line 79
5.at Swift_Mailer->send(object(Swift_Message), array()) in Mailer.php line 395
6.at Mailer->sendSwiftMessage(object(Swift_Message)) in Mailer.php line 181
7.at Mailer->send('emails.auth.verify', array('title' => 'Email verification', 'intro' => 'To validate your email ', 'link' => 'click on this link', 'confirmation_code' => 'txbS57Wlf5iYPCsBk3Q9e7byQnDLDC'), object(Closure)) in SendMail.php line 50
8.at SendMail->handle(object(Mailer))
9.at call_user_func_array(array(object(SendMail), 'handle'), array(object(Mailer))) in Container.php line 503
10.at Container->call(array(object(SendMail), 'handle')) in Dispatcher.php line 193
11.at Dispatcher->Illuminate\Bus\{closure}(object(SendMail))
12.at call_user_func(object(Closure), object(SendMail)) in Pipeline.php line 139
13.at Pipeline->Illuminate\Pipeline\{closure}(object(SendMail))
14.at call_user_func(object(Closure), object(SendMail)) in Pipeline.php line 103
15.at Pipeline->then(object(Closure)) in Dispatcher.php line 205
16.at Dispatcher->dispatchNow(object(SendMail), null) in Dispatcher.php line 178
17.at Dispatcher->dispatch(object(SendMail)) in DispatchesJobs.php line 17
18.at Controller->dispatch(object(SendMail)) in AuthController.php line 110
19.at AuthController->postRegister(object(RegisterRequest), object(UserRepository))
20.at call_user_func_array(array(object(AuthController), 'postRegister'), array(object(RegisterRequest), object(UserRepository))) in Controller.php line 256
21.at Controller->callAction('postRegister', array(object(RegisterRequest), object(UserRepository))) in ControllerDispatcher.php line 164
22.at ControllerDispatcher->call(object(AuthController), object(Route), 'postRegister') in ControllerDispatcher.php line 112
23.at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
24.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
25.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in RedirectIfAuthenticated.php line 41
26.at RedirectIfAuthenticated->handle(object(Request), object(Closure))
27.at call_user_func_array(array(object(RedirectIfAuthenticated), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
28.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
29.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
30.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 114
31.at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'postRegister') in ControllerDispatcher.php line 69
32.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Auth\AuthController', 'postRegister') in Route.php line 203
33.at Route->runWithCustomDispatcher(object(Request)) in Route.php line 134
34.at Route->run(object(Request)) in Router.php line 708
35.at Router->Illuminate\Routing\{closure}(object(Request))
36.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
37.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
38.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
39.at Pipeline->then(object(Closure)) in Router.php line 710
40.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 675
41.at Router->dispatchToRoute(object(Request)) in Router.php line 635
42.at Router->dispatch(object(Request)) in Kernel.php line 236
43.at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
44.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
45.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in App.php line 56
46.at App->handle(object(Request), object(Closure))
47.at call_user_func_array(array(object(App), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
48.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
49.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 17
50.at VerifyCsrfToken->handle(object(Request), object(Closure))
51.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
52.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
53.at ShareErrorsFromSession->handle(object(Request), object(Closure))
54.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
55.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
56.at StartSession->handle(object(Request), object(Closure))
57.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
58.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
59.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
60.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
61.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
62.at EncryptCookies->handle(object(Request), object(Closure))
63.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
64.at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
65.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
66.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
67.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
68.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
69.at Pipeline->then(object(Closure)) in Kernel.php line 122
70.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
71.at Kernel->handle(object(Request)) in index.php line 53

Many thanks

**Comment by bestmomo** [comment]
Hi,

Look at your Email configuration in config/mail.php.

**Comment by chenchaochen** [comment]
I actually set this up when I first downloaded your application last month, but it didn't work. Maybe it's my mail.php settings problem (I use smpt.gmail.com port 587). I will give it a try though. 

Thanks a lot, I appreciate it.
