### ISSUE TITLE
Error on FileManager Publish

### ISSUE THREAD

**Issue by lonAlbert** [bestmomo/laravel5-example#43]
I got this error upon running: "php artisan vendor:publish":

PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('log')
#1 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array)
#2 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array)
#3 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php(845): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\C in /home/lon/redact/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736

**Comment by bestmomo** [comment]
Look into your .env file, if you have some space enclose the value in double quotes.

**Comment by lonAlbert** [comment]
Wow! thanks it worked!
