### ISSUE TITLE
User Folder access

### ISSUE THREAD

**Issue by lonAlbert** [bestmomo/laravel5-example#44]
Hi, this is not exactly an issue, but I've been trying to implement folder access based on user in my web app using this example as a template.
I want each user to have a new folder based off the username in the userfiles directory upon creation and be able to access only that folder.
I can't get my head around how to do that and also how the functions accessMediasFolder() and accessMediasAll() are working with the filemanager. I am using ckeditor and FileManager(v 2.3.0).

**Comment by bestmomo** [comment]
Hi,
You can see the interesting code in public/filemanager/connectors/php/default.config.php. For each user is created a folder with name.id and he can only access to this folder.

**Comment by lonAlbert** [comment]
Wow! thanks so much for the quick response! I've been floating back and forth between the FileManager github page and my code trying to figure it out for hours! Thank you mate, this would do!

**Comment by deepakgarg9121** [comment]
I am not able to access any folder in file manager.only loading screen comes in right side.
