### ISSUE TITLE
baseUrl config in filemanager.config.js

### ISSUE THREAD

**Issue by lonAlbert** [bestmomo/laravel5-example#45]
Hi again mate, thanks so much for your help previously, there's an issue with the filemanager.config.js file. Whenever a new file is uploaded whne using the manager, the file url is prefixed with "/filemanager/", hence it can't be previewed since the url is wrong. I changed my baseUrl in filemanager.config.js to 
 "baseUrl": false,
to get it to work.

**Comment by bestmomo** [comment]
Hi,
I've already met this issue that happens on some servers. I dont know why.

**Comment by lonAlbert** [comment]
Alright then, thanks!
