### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by abdkhakim** [bestmomo/laravel5-example#49]
in FormBuilder.php line 1110: Call to a member function toArray() on null
how i can fix it?

**Comment by bestmomo** [comment]
Hello,
Looks like a model bindig issue, what is the context ?

**Comment by abdkhakim** [comment]
Whoops, looks like something went wrong.
1/1 FatalErrorException in FormBuilder.php line 1110: Call to a member function toArray() on null 

when log in, open message and others
sorry, but im newbie in here
ty

**Comment by bestmomo** [comment]
I think there is something with installation, try reinstal.
