### ISSUE TITLE
FatalErrorException in Container.php line 702

### ISSUE THREAD

**Issue by dominykasgel** [bestmomo/laravel5-example#50]
Hi there,

I installed your app according your Installation notes. Front-end works fine, but when I go to /public/admin/ I get this error: FatalErrorException in Container.php line 702: Maximum function nesting level of '100' reached, aborting!

Stacktrace: http://pastebin.com/RmNYQxpg

What might be wrong?

**Comment by bestmomo** [comment]
Hi,

I think it's a xdebug issue. Try change max value or remove it.

**Comment by dominykasgel** [comment]
Thanks a lot. It helped to resolve the issue.
