### ISSUE TITLE
How to use filemanager?

### ISSUE THREAD

**Issue by lyhongpon** [bestmomo/laravel5-example#51]
To use filemanager is to click button Brows Server? 
After I click on the button, there is a window show up with url http://localhost:8000/filemanager/index.html?CKEditor=content&CKEditorFuncNum=93&langCode=en with Error 404 Page does not exist.

Is what I do wrong? or I need to do additional configurations?

**Comment by bestmomo** [comment]
Did you use this command on installation ?
```
php artisan vendor:publish
```
