### ISSUE TITLE
bug when listing the articles at the back-end with more than 10 articles and then when sorting the articles (by date, title, author...) : the paginator links disappear and you cannot go through all the articles...

### ISSUE THREAD

**Issue by Maestroil** [bestmomo/laravel5-example#56]
Hi,
I'm a newcomer.

I see an issue in your program when listing the articles at the back-end with more than 10 articles and then when sorting the articles (by date, title, author...) : the paginator links disappear and you cannot go through all the articles.

I think the issue is located somewhere within BlogController@indexOrder when the request is an ajax one coming from the view "back.blog.index" : the 'links' (BlogController line 103) seems not being transferred well to the view "back.blog.index" (back.blog.index line 147)

The quick fix is to put a higher number n in paginate... but this does not solve the problem really... 

Have you an idea for a definite repair ?
Thanks!
Maestroil

**Comment by bestmomo** [comment]
Hi,

Right, there was some framework evolution since I wrote this code. Now it's ok with [this commit](https://github.com/bestmomo/laravel5-example/commit/e597f115e1ddb341908461d6867dd4783193a341)
