### ISSUE TITLE
Login page is giving error

### ISSUE THREAD

**Issue by flik** [bestmomo/laravel5-example#57]
TokenMismatchException in VerifyCsrfToken.php line 67:

**Comment by bestmomo** [comment]
Hello,
Can you add some context for this error ?

**Comment by flik** [comment]
I was trying to open admin section and It was coming when I submitted login information.

**Comment by bestmomo** [comment]
Looks like a session issue, check your session parameters.

**Comment by grolock51** [comment]
How do  you get to the admin section?

**Comment by flik** [comment]
Now, It is fine. I think, error was because of cache.
