### ISSUE TITLE
Translations in the database

### ISSUE THREAD

**Issue by UnrulyNatives** [bestmomo/laravel5-example#6]
Well, I decided to stick to this project and contribute to its development.

I am now upgrading from Laravel 4.2. I have a large amount of translations in the database, made with 
https://github.com/Waavi/translation

In my opinion the necessary feature is MIXED solution (database and files), which I use very often. 

What are your plans in regard of translations stored in DB?
Do you consider using https://github.com/dimsav/laravel-translatable?

**Comment by bestmomo** [comment]
Thank you to contribute to this project.

It's a big work to changes all french items in code !

I did not ask me about multilingual model instances.  I'll have a look to this package. But packages have some issues for now to publish config on L5. I want to wait until L5 package system is done.

**Comment by UnrulyNatives** [comment]
Now when L5 is finally released, can we create a solution described in my initial post? 
I means sth to replace Waavi functionality.
