### ISSUE TITLE
Swift_TransportException in AbstractSmtpTransport.php line 383

### ISSUE THREAD

**Issue by manan88** [bestmomo/laravel5-example#62]
I have created new user from front side and getting following error.

```
Swift_TransportException in AbstractSmtpTransport.php line 383:
Expected response code 220 but got code "554", with message "554 5.7.1 <unknown[49.213.40.11]:52491>: Client host rejected: Access denied
```

Any idea how to fix this problem?

Thanks.

**Comment by bestmomo** [comment]
Check your email settings, look at [this post](http://stackoverflow.com/questions/29100877/trying-to-get-laravel-5-email-to-work).
