### ISSUE TITLE
$posts->created_at only display date without time

### ISSUE THREAD

**Issue by LeePower** [bestmomo/laravel5-example#67]
Hi, first of all, thank you for this great tutorial, really help me to learn Laravel a lot faster!

I'm trying to display the hour, minute, second with the date format like this (Y/M/D H:M:S) in resources/views/front/blog/index.blade.php

I was be able to retrieve the 'created_at' from DB that looks like this "2016-05-25 15:35:51"

And when prints out using dd(posts->created_at) I can still see it's been stored as "2016-05-25 15:35:51"

But how come when I use blade template {{ post->created_at}} it only uses the date as 05/25/2016 without the hour, minute, second

Tried to use strtotime but still no luck.

**Comment by bestmomo** [comment]
Hi,
The **Post** model uses a **DatePresenter** trait, you can find it in **app/Presenters**. You can change date format there or even stop to use this trait.

**Comment by LeePower** [comment]
Got it, thanks for the heads up!
